export const FORM_FIELD_REQUEST="FORM_FIELD_REQUEST";
export const FORM_FIELD_SUCCESS="FORM_FIELD_SUCCESS";
export const FORM_FIELD_FAILURE="FORM_FIELD_FAILURE";

export const CLEAR_ERRORS="CLEAR_ERRORS";